"""Bake computed results + geometry into site/data.js and copy media.

Collects whatever exists in out/ (drafting map, dynamics, 2D stats, 3D
gallery npz metadata + force stats, bird study) plus mesh silhouettes for
the live 2D lab. Re-run after any production run finishes; the site never
shows placeholder numbers — sections whose data is missing say so.
"""
import csv
import json
import shutil
from pathlib import Path

import numpy as np

SITE = Path("site")
OUT = Path("out")
DATA = {}


def silhouettes():
    """Side/top projections of the gallery meshes as run-length strings."""
    from geometry import from_mesh
    from run_shapes3d import OBJECTS
    sils = {}
    for name, cfg in OBJECTS.items():
        if cfg["mesh"] is None:
            continue
        L = 220
        pad = 60
        rot = [("x", cfg["aoa"])] if cfg.get("aoa") else None
        mask, _ = from_mesh(Path("assets/meshes") / cfg["mesh"],
                            (L + pad, L + pad, L + pad), L,
                            rotate=rot, axes=cfg.get("axes"),
                            flips=cfg.get("flips"))
        for view, ax in (("side", 1), ("top", 2)):
            proj = mask.any(axis=ax)
            nz = np.nonzero(proj)
            x0, x1 = nz[0].min(), nz[0].max()
            y0, y1 = nz[1].min(), nz[1].max()
            crop = proj[x0:x1 + 1, y0:y1 + 1]
            # pack rows as run-length: "start:len,start:len;..." per row
            rows = []
            for r in range(crop.shape[1]):
                col = np.nonzero(crop[:, r])[0]
                runs = []
                if len(col):
                    s = p = col[0]
                    for c in col[1:]:
                        if c != p + 1:
                            runs.append(f"{s}:{p - s + 1}"); s = c
                        p = c
                    runs.append(f"{s}:{p - s + 1}")
                rows.append(",".join(runs))
            sils[f"{name}_{view}"] = {
                "w": int(crop.shape[0]), "h": int(crop.shape[1]),
                "rows": ";".join(rows),
            }
    return sils


def main():
    # 2D cylinder stats
    if (OUT / "results2d.json").exists():
        DATA["cylinder2d"] = json.load(open(OUT / "results2d.json"))
    # drafting map
    if (OUT / "drafting_map.csv").exists():
        DATA["drafting"] = list(csv.DictReader(open(OUT / "drafting_map.csv")))
    # dynamics
    if (OUT / "dynamics.csv").exists():
        DATA["dynamics"] = list(csv.DictReader(open(OUT / "dynamics.csv")))
    # 3D gallery: metadata + tail-averaged forces
    gallery = {}
    for npz in sorted(OUT.glob("shape_*.npz")):
        name = npz.stem.replace("shape_", "")
        with np.load(npz, allow_pickle=False) as d:
            meta = json.loads(str(d["meta"]))
        fcsv = OUT / f"forces_{name}.csv"
        if fcsv.exists():
            arr = np.genfromtxt(fcsv, delimiter=",", names=True)
            tail = arr[-5000:]
            meta["Cd_mean"] = float(np.mean(tail["Cd"]))
            meta["Cd_std"] = float(np.std(tail["Cd"]))
            meta["Cl_mean"] = float(np.mean(tail["Cl"]))
        gallery[name] = meta
    if gallery:
        DATA["gallery"] = gallery
    # birds
    for k, fn in (("birdsGate", "birds_gate.json"),
                  ("birdsBaseline", "birds_baseline.json"),
                  ("birdsFormation", "birds_formation.json")):
        if (OUT / fn).exists():
            DATA[k] = json.load(open(OUT / fn))
    # silhouettes (always available once meshes exist)
    DATA["silhouettes"] = silhouettes()
    # media copies
    media = SITE / "media"
    media.mkdir(exist_ok=True)
    models = media / "models"
    models.mkdir(exist_ok=True)
    for glb in Path("assets/meshes").glob("*.glb"):
        shutil.copy2(glb, models / glb.name)
    vids = []
    for mp4 in sorted(OUT.glob("*.mp4")):
        shutil.copy2(mp4, media / mp4.name)
        vids.append(mp4.name)
    DATA["videos"] = vids
    (SITE / "data.js").write_text(
        "// generated by tools/build_site_data.py — do not edit\n"
        "window.SITE_DATA = " + json.dumps(DATA) + ";\n")
    print("wrote site/data.js:",
          {k: (len(v) if hasattr(v, "__len__") else "obj") for k, v in DATA.items()})


if __name__ == "__main__":
    main()
