"""Bake the golden cross-validation cases into site/golden.js.

The three pinned cases exercise disjoint physics: Taylor-Green = bulk
(collision+streaming), Poiseuille = walls, cylinder = open BCs + forces.
Parameters and tolerances match the pytest suite exactly; the Python-measured
Strouhal number is read from out/results2d.json once that run has finished.
Re-run this script whenever results change. No fetch(): file:// pages can't
read JSON, so this is a .js global.
"""
import json
from pathlib import Path

py_st = None
res2d = Path("out/results2d.json")
if res2d.exists():
    py_st = json.load(open(res2d))

golden = {
    "taylorGreen": {
        "n": 64, "tau": 0.8, "u0": 0.03, "steps": 800,
        # fp32 justification: rate fit error is ~1e-4 in fp64; fp32 rounding
        # adds <0.5%; the physics tolerance stays the Python suite's 2% with
        # a 0.5% fp32 allowance.
        "tol": 0.025,
        "targetFormula": "2*nu*k^2, nu=(tau-1/2)/3, k=2*pi/n",
    },
    "poiseuille": {
        "nx": 8, "ny": 33, "tau": 0.9, "g": 1e-6, "steps": 8000, "tol": 0.02,
        "targetFormula": "u(y)/u_max = 1-(y/h)^2",
    },
    "strouhal": {
        "nx": 400, "ny": 160, "D": 20, "Deff": 22, "U": 0.08, "Re": 100,
        "steps": 30000, "warmup": 10000, "band": [0.14, 0.20],
        "pythonSt": py_st["St"] if py_st else None,
        "pythonCd": py_st["Cd_mean"] if py_st else None,
        "blockage": py_st["blockage"] if py_st else 22 / 160,
    },
}

out = Path("site/golden.js")
out.write_text("// generated by tools/export_golden.py — do not edit\n"
               "window.GOLDEN = " + json.dumps(golden, indent=1) + ";\n")
print("wrote", out, "pythonSt =", golden["strouhal"]["pythonSt"])
